spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/companies

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

  liquibase:
    liquibase-schema: liquibase

  mvc:
    format:
      date-time: iso
      date: iso
    hiddenmethod:
      filter:
        enabled: true

  mail:
    default-encoding: UTF-8
    host: ${emailHost}
    username: ${emailUsername}
    password: ${emailPassword}
    port: 465
    protocol: smtps
    properties.mail.debug: true

